- name: Up Service grafana
  register: container_status
  command: docker-compose -f /home/onepiece/Documents/Ansible-Tutorial/dockprom/docker-compose-grafana.yml up -d

- debug: msg="{{ container_status.stdout }}"