- name: Up Service node exporter
  register: container_status
  command: docker-compose -f /home/onepiece/Documents/Ansible-Tutorial/dockprom/docker-compose-nodeexporter.yml up -d 

- debug: msg="{{ container_status.stdout }}"